language: python
os: linux
dist: focal
addons:
  apt:
    packages:
    - libre2-5  # for google-re2
    - libre2-dev  # for google-re2
    - pybind11-dev  # for google-re2
python:
- '3.8'
install:
- pip uninstall -y black pyflakes isort pytest pytest-asyncio  # Wipe Travis environment
- pip install black pyflakes isort pytest~=6.0 pytest-asyncio~=0.14.0
- pip install -e .[maintenance]
- pip freeze
script:
- pyflakes .
- black --check .
- isort --check-only --diff cjwmodule tests
- pytest --verbose
- ./setup.py extract_messages --check
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: RxssmFQIFKH8NbQgtpBgjZFeFLfWoaZuMuiBy0a/XWkcqh0fCqvfJB8t9lD42PYs08kpkPK+7Dasl+44zc9kb0sugGhBjMJQ6Gjy4joY4L/vRsCqF4Q9sQOKW0xrgA6bKMP//9KMPEwC7NDBz4jvaS6J1S3z3HSOD6B0oSdsLhNLFF8Rebj61dRgR/dyg8wDAzTlx0UVEKQ+q+orrWDZQOUO1XjpNgkZKtzt5vfNzPF8dyhZVqrRKT9uw47UCixbMcdoOs0TpWzs6aGXcyjTT4wt3xSA7tBnXpowmNrJLhdsFFlSDb5rpvbawT5HmgeexaWZsU7XyD5QMo82D/6oSpSNacZQYCUrdBhyZJsRPhIubbTmeGvQrc2OpH95QknMQ3dokmz+wNBdQA8VDKHv3aFPWH0AkJvCGgE7SzelJGBDwSuv3LitOG4VeGs0akm7s9uGFIAZOU+By0/hVcEAz+0ifd2f6JGcvmi92UtRjWTDihfJVbgk2qCI8Q+jARlQ+GWOcSOxPAd/3qblR6jJVaUvofQU+7Lu+S91NhzinfDDVemugXkQm5SNJHr41XxhSVVjAFsZ4QKKWgMh+FCun3LG6MpsLywic0ZXtTffLBKZPKKYA6UXz9jqPQT7zbmx+tsNe12QEcl6vI4q1anFNir//zmHPi+NL0uN6pdTtA4=
