language: python
os: linux
dist: focal
python:
- '3.8'
before_install: python -mpip install poetry tox-travis
install: poetry install -v
script: tox
jobs:
  include:
    - stage: deploy
      python: "3.8"
      before_install: python -mpip install poetry
      install: skip
      script: skip
      before_deploy:
        - poetry version $(git describe --tags --exact-match --match="v*.*.*" | cut -b2-)  # fallback "" means, "0.0.0"
        - poetry config pypi-token.pypi "$PYPI_TOKEN"
      deploy:
        skip_cleanup: true  # so "poetry version" stays
        provider: script
        script: poetry publish --build
        on:
          tags: true
